# Generated by Django 5.2.4 on 2025-09-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='user_posts', to='blog.post'),
        ),
    ]
