# Generated by Django 5.2.4 on 2025-09-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_users_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following_user', to='blog.users'),
        ),
        migrations.AddField(
            model_name='users',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers_user', to='blog.users'),
        ),
    ]
