# Generated by Django 5.2.4 on 2025-09-27 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_message',
            name='user',
        ),
        migrations.AddField(
            model_name='chat_message',
            name='chat',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='chats.chat_list'),
            preserve_default=False,
        ),
    ]
