# Generated by Django 5.2.4 on 2025-09-27 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_users_followers_users_following'),
        ('chats', '0002_remove_chat_message_user_chat_message_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_message',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.users'),
            preserve_default=False,
        ),
    ]
