# Generated by Django 5.2.4 on 2025-09-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_chat_message_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_message',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
