# Generated by Django 5.2.4 on 2025-09-27 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_alter_chat_message_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat_message',
            old_name='chat',
            new_name='chat_id',
        ),
    ]
