# Generated by Django 5.2.4 on 2025-09-28 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_users_followers_users_following'),
        ('chats', '0005_rename_chat_chat_message_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_message',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='blog.users'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat_message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='blog.users'),
        ),
    ]
