# Generated by Django 5.2.4 on 2025-09-28 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_chat_message_receiver_alter_chat_message_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_message',
            name='receiver',
        ),
    ]
