# Generated by Django 5.2.4 on 2025-10-01 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_users_followers_users_following'),
        ('chats', '0007_remove_chat_message_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_list',
            name='users',
        ),
        migrations.AddField(
            model_name='chat_list',
            name='resever',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_resever', to='blog.users'),
        ),
        migrations.AddField(
            model_name='chat_list',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sender', to='blog.users'),
        ),
    ]
