# Generated by Django 5.2.4 on 2025-10-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_users_followers_users_following'),
        ('chats', '0008_remove_chat_list_users_chat_list_resever_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_list',
            name='resever',
        ),
        migrations.RemoveField(
            model_name='chat_list',
            name='sender',
        ),
        migrations.AddField(
            model_name='chat_list',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='chat_users', to='blog.users'),
        ),
    ]
